#ifndef _ULTRASONIC_H_
#define _ULTRASONIC_H_

#define ULTRASONIC_TRIGGER_PORT PORTD
#define ULTRASONIC_TRIGGER_DDR  DDRD
#define ULTRASONIC_TRIGGER_PIN  6

#define ULTRASONIC_ECHO_PORT    PORTE
#define ULTRASONIC_ECHO_DDR     DDRE
#define ULTRASONIC_ECHO_PIN     4     // PE4

//#define ULTRASONIC_TRIGGER_PIN  PIND

void setupHC_SR04();

#endif // _ULTRASONIC_H_